import { Navbar } from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://bootswatch.com/5/flatly/bootstrap.min.css" rel="stylesheet"/>
      </head>
      <body>
        <Navbar/>
        {children}
     </body>
    </html>
  )
}
